### ISSUE TITLE
When running a domain multiple times, number of subdomains alter and difference is significant.

### ISSUE THREAD

**Issue by within-cells-interlink-ed** [m8sec/subscraper#22]

**Comment by zexceed012** [comment]
You can see the difference in the ss below.
![image](https://user-images.githubusercontent.com/90812860/203923615-f19ebcf1-1211-4edf-be60-eb9b1f4f03d2.png)

Here is difference for different domain.
![image](https://user-images.githubusercontent.com/90812860/203923979-46a08038-9fe9-4572-bf57-8b6f876ed36b.png)

**Comment by m8sec** [comment]
Can you provide any addition information on how this is being executed, duration, etc.

If the subhandler thread was cut early that could be annissue. Alternatively, and more likely, many modules are based on web requests or search scraping that could be blocked after multiple attempts in a row - if that accounts for a large number of results it could be causing the problem.

**Comment by m8sec** [comment]
Closing inactive.
